export const Schools = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "University of Ilorin (UNILORIN)",
  "Ahmadu Bello University (ABU Zaria)",
  "University of Nigeria Nsukka (UNN)",
  "Lagos State University (LASU)",
  "Olabisi Onabanjo University (OOU)",
  "University of Benin (UNIBEN)",
  "University of Port Harcourt (UNIPORT)",
  "Federal University of Technology Akure (FUTA)",
  "Federal University of Technology Minna (FUTMINNA)",
  "Federal University of Technology Owerri (FUTO)",
  "Kwara State University (KWASU)",
  "Federal University Dutse",
  "Federal University Lafia",
  "Federal University Oye-Ekiti (FUOYE)",
  "University of Calabar (UNICAL)",
  "University of Jos (UNIJOS)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Ekiti State University (EKSU)",
  "Osun State University (UNIOSUN)",
  "Adekunle Ajasin University (AAUA)",
  "Ambrose Alli University (AAU Ekpoma)",
  "Bayero University Kano (BUK)",
  "Benue State University (BSU)",
  "Delta State University (DELSU)",
  "Rivers State University (RSU)",
  "Kaduna State University (KASU)",
  "Yaba College of Technology (YABATECH)",
  "Federal Polytechnic Ilaro",
  "Federal Polytechnic Ede",
  "Kwara State Polytechnic",
  "Auchi Polytechnic",
  "Lagos State Polytechnic (LASPOTECH)",
  "Federal Polytechnic Ado-Ekiti",
  "Osun State College of Technology",
  "College of Health Technology Offa",
  "College of Health Technology Ibadan",
  "School of Health Technology Kano",
  "College of Education Ilorin",
  "College of Education Oro",
  "Federal College of Education Oyo",
  "Federal College of Education Zaria",
  "Nigerian Defence Academy (NDA)",
  "National Open University of Nigeria (NOUN)",
  "Babcock University",
  "Covenant University",
  "Bowen University",
  "Redeemer’s University",
  "Joseph Ayo Babalola University"
];



export const Courses = [
  "Agricultural Economics",
  "Animal Science",
  "Crop Science",
  "Soil Science",
  "Agronomy",
  "Fisheries and Aquaculture",
  "Forestry and Wildlife Management",
  "Microbiology",
  "Biochemistry",
  "Industrial Chemistry",
  "Computer Science",
  "Software Engineering",
  "Cybersecurity",
  "Information Technology",
  "Electrical and Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Agricultural Engineering",
  "Petroleum Engineering",
  "Architecture",
  "Estate Management",
  "Urban and Regional Planning",
  "Quantity Surveying",
  "Building Technology",
  "Nursing Science",
  "Medicine and Surgery",
  "Pharmacy",
  "Medical Laboratory Science",
  "Public Health",
  "Physiotherapy",
  "Radiography",
  "Health Information Management",
  "Anatomy",
  "Physiology",
  "Law",
  "Mass Communication",
  "Political Science",
  "Sociology",
  "Psychology",
  "Economics",
  "Accounting",
  "Business Administration",
  "Marketing",
  "Banking and Finance",
  "Entrepreneurship",
  "Human Resource Management",
  "Education Management",
  "Early Childhood Education",
  "English Language",
  "History and International Studies"
];
